### ISSUE TITLE
Wrong data Format - All data inside Public Address, should be in Wallet

### ISSUE THREAD

**Issue by apoorvq** [inbloxme/password-based-tx-sign#13]
https://github.com/inbloxme/password-based-tx-sign/blob/7ae210f26727ab8a7a225a57c9f284026c2e00a8/index.js#L25

**Comment by apoorvq** [comment]
wallet: address, privateKey, mnemonic, wallet

**Comment by ARJUN-R34** [comment]
> wallet: address, privateKey, mnemonic, wallet

There cannot exist 2 different keys with the same name.

The response structure looks like this,
```response: {
    publicAddress: address,                 #public address
    privateKey,                                     #private key
    mnemonic,                                     #12 word seed phrase
    wallet: {  }                                       #other wallet details
}```
